#输入的视频文件
input: D:\PyCharm\workplace\Fed_Learn\auto_ai_subtitle\video\test3.mp4
#中间过程会生成的音频文件
output: D:\PyCharm\workplace\Fed_Learn\auto_ai_subtitle\video\test3-1.mp3
#生成的原始字幕文件
srt_path: D:\PyCharm\workplace\Fed_Learn\auto_ai_subtitle\video\test3-1.srt
#生成的翻译后的字幕文件
srt_translate_path: D:\PyCharm\workplace\Fed_Learn\auto_ai_subtitle\video\test3-1-zh.srt
#翻译时开启多少线程
translate_threads: 10
#翻译源语言
from: ja
#翻译目标语言
to: zh
#huggingface model地址，例如 D:\download\pytorch_model.bin
hf_model_path: ""
model_download_path: checkpoints/whisper
#devive: cuda, cpu
device: cpu
